const attributes = [
  ["id", "varchar(255)", "PRIMARY KEY"],
  ["title", "varchar(255)", "NOT NULL"],
  ["description", "text"],
  ["summary", "text"],
  ["installs", "varchar(60)"],
  ["min_installs", "int"],
  ["max_installs", "int"],
  ["score", "numeric"],
  ["ratings", "int"],
  ["reviews", "int"],
  ["histogram", "hstore"],
  ["price", "numeric", "DEFAULT 0"],
  ["currency", "varchar(3)"],
  ["available", "boolean", "DEFAULT true"],
  ["android_version", "varchar(10)"],
  ["developer_id", "varchar(255)", "REFERENCES developers(id)"],
  ["genre", "varchar(20)"],
  ["genre_id", "varchar(50)"],
  ["categories", "json"],
  ["icon", "text"],
  ["header_image", "text"],
  ["screenshots", "text []"],
  ["video", "text"],
  ["video_image", "text"],
  ["preview_video", "text"],
  ["content_rating", "varchar(30)"],
  ["content_rating_description", "text"],
  ["released", "date"],
  ["updated", "bigint"],
  ["version", "varchar(20)"],
  ["recent_changes", "text"],
  ["comments", "text []"],
  ["url", "text"],
];

// const appSchema = `(
//     id varchar(255),
//     title varchar(255),
//     description text,
//     summary text,
//     installs varchar(60),
//     minInstalls int,
//     maxInstalls int,
//     score numeric,
//     ratings int,
//     reviews int,
//     histogram hstore,
//     price numeric,
//     currency varchar(3),
//     available boolean,
//     androidVersion varchar(10),
//     developerId varchar(255),
//     genre varchar(20),
//     genreId varchar(50),
//     categories json,
//     icon text,
//     headerImage text,
//     screenshots text [],
//     video text,
//     videoImage text,
//     previewVideo text,
//     contentRating varchar(30),
//     contentRatingDescription text,
//     released date,
//     updated bigint,
//     version varchar(20),
//     recentChanges text,
//     comments text [],
//     url text,
//     PRIMARY KEY (id),
//     FOREIGN KEY (developerId) REFERENCES developer(id)
// )`;
module.exports = attributes;
